services:
  product-service:
    build: .
    container_name: product-service
    command: python product.py
    ports:
      - "5001:5001"

  order-service:
    build: .
    container_name: order-service
    command: python order.py
    ports:
      - "5002:5002"